### ISSUE TITLE
Formato de schema para blocos

### ISSUE THREAD

**Issue by filiperochalopes** [hmlem/protocolos#3]
A ideia é manter um protocolo inteiro em um arquivo yml, deve ter como:
- Ter link para outros protocolos `[link](referencia)`
- Ter entrada para variáveis externas como peso para cálculo de medicações e cargas de energia: altura, peso, idade
- Ter campos de blocos
- Ter campos de relacionamentos

**Comment by filiperochalopes** [comment]
```yml
metadata:
    title: "Título do Protocolo"
    description: "Descrição da utilidade e para quê abrir o protocolo"
boxes:
    1:
        description: "Parada cardiorespiratória"
        references: "Teste de referência"
        style: "default"       
drugs:
    amiodarona_1:
        name: "Amiodarona ampola X"
        concentration: "150mg/mL"
        volumeMl: "2mL"
        administration: "Em bólus rápido com push de soro fisiológico"
        dose:
            usual: "({{weight}}*20) mg"
            max: "300mg"
relationships:
    - "{{1}} - Sim -> {{2}}"
    - "{{1}} - Não -> {{3}}"
    - "{{2}} -> {{5}}"
styles:
    default: 
        - backgroundColor: "#fff"
        - borderRadius: "5px"
        - border: "1px solid #ccc"
        - format: "square|rectangle|circle|hexagon"
        - fixedWidth: "small|medium|big|64px"
```

**Comment by ghost** [comment]
Acredito que seja melhor seguir uma estrutura semelhante a uma arvore binária. Ao invés de descrever as relações em um campo separado, informar na estrutura da _box_ com informações como: '_from_' e '_to_'. Nesse sentido, também seria necessário diferenciar o tipo da _box_ . Pela estrutura percebi que só há dois: simples e de decisão. Poderia ser adicionada a informação _type_ na estrutura da _box_.

**Comment by filiperochalopes** [comment]
Eu pensei na ideia de modelagem de banco para fazer os relacionamentos separados, penso ser mais escalável. Como vc faria se uma decisão pode ir para mais de um Box?

**Comment by ghost** [comment]
Colocaria o tipo para _decision_ e adicionaria dois campos para indicar para onde iria. Semelhante a estrutura abaixo. Esta descreve o fluxograma da imagem.

```yml
# 4 types of actions: beginning, simple, decision, and end.
metadata:
  title: "Título do Protocolo"
  description: "Descrição da utilidade e para quê abrir o protocolo"\
  autor: "Joao Batista"
actions:
  A:
    description: null
    reference: null
    type: beginning 
    from: null
    to: B
  B: 
    description: "B"
    reference: ""
    type: decision 
    from: A
    yesTo: C
    noTo: E
  C: 
    description: "C"
    reference: ""
    type: simple 
    from: B
    to: D
  D: 
    description: null
    reference: null
    type: end 
    from: C
    to: null
  E: 
    description: "E"
    reference: "E"
    type: simple 
    from: B
    to: F
  F: 
    description: null
    reference: ""
    type: end
    from: E
    to: null
```
![eabb8716-5137-4d49-bcd6-0cef9089f917](https://user-images.githubusercontent.com/13579770/212772840-f86f7158-0444-4766-96a3-74d9dac3a7ab.jpg)
